"""
Telemetry Module

Prometheus metrics and event broadcasting for Glass-Box observability.
"""

import time
from collections.abc import Callable
from contextlib import asynccontextmanager
from functools import wraps

from prometheus_client import Counter, Gauge, Histogram

# =============================================================================
# Per-Agent Prometheus Metrics (Glass-Box Core)
# =============================================================================

AGENT_INVOCATIONS = Counter(
    "orchestrator_agent_invocations_total",
    "Total number of agent invocations",
    ["agent"],
)

AGENT_DURATION = Histogram(
    "orchestrator_agent_duration_seconds",
    "Agent execution duration in seconds",
    ["agent"],
    buckets=[0.5, 1, 2, 5, 10, 30, 60, 120],
)

AGENT_TOKENS = Counter(
    "orchestrator_agent_tokens_total",
    "Total tokens generated per agent",
    ["agent"],
)

AGENT_ERRORS = Counter(
    "orchestrator_agent_errors_total",
    "Total errors per agent",
    ["agent"],
)

AGENT_CURRENT = Gauge(
    "orchestrator_current_agent",
    "Currently active agent (1=active, 0=idle)",
    ["agent"],
)

# Orchestration-level metrics
ORCHESTRATION_REQUESTS = Counter(
    "orchestrator_requests_total",
    "Total orchestration requests",
)

ORCHESTRATION_SUCCESSES = Counter(
    "orchestrator_successes_total",
    "Successful orchestration completions",
)

ORCHESTRATION_FAILURES = Counter(
    "orchestrator_failures_total",
    "Failed orchestration attempts",
)

ORCHESTRATION_RETRIES = Counter(
    "orchestrator_retries_total",
    "Total retry attempts",
)


# =============================================================================
# Telemetry Context Manager
# =============================================================================


@asynccontextmanager
async def track_agent(agent_name: str):
    """
    Context manager for tracking agent execution.

    Usage:
        async with track_agent("coder"):
            await agent.invoke(state)
    """
    # Set current agent gauge
    AGENT_CURRENT.labels(agent=agent_name).set(1)
    AGENT_INVOCATIONS.labels(agent=agent_name).inc()

    start_time = time.perf_counter()
    try:
        yield
    except Exception:
        AGENT_ERRORS.labels(agent=agent_name).inc()
        raise
    finally:
        duration = time.perf_counter() - start_time
        AGENT_DURATION.labels(agent=agent_name).observe(duration)
        AGENT_CURRENT.labels(agent=agent_name).set(0)


def record_tokens(agent_name: str, count: int) -> None:
    """Record tokens generated by an agent."""
    AGENT_TOKENS.labels(agent=agent_name).inc(count)


# =============================================================================
# Decorator for Agent Methods
# =============================================================================


def tracked_agent(agent_name: str) -> Callable:
    """Decorator to track agent invocations."""

    def decorator(func: Callable) -> Callable:
        @wraps(func)
        async def wrapper(*args, **kwargs):
            async with track_agent(agent_name):
                return await func(*args, **kwargs)

        return wrapper

    return decorator
